"""initial migration

Revision ID: fab3295ff679
Revises:
Create Date: 2021-11-22 23:24:17.080022

"""
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = "fab3295ff679"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column(
            "created", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "touched", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("section_id", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("type", mysql.TINYINT(display_width=2), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=45), nullable=True),
        sa.Column("forum_priority", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=45), nullable=False),
        sa.Column("password", sa.VARBINARY(length=60), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=False),
        sa.Column("timezone", sa.String(length=50), nullable=False),
        sa.Column("last_activity", mysql.INTEGER(unsigned=True), nullable=False),
        sa.Column("login_time", sa.DateTime(), nullable=True),
        sa.Column("logout_time", sa.DateTime(), nullable=True),
        sa.Column("status", mysql.TINYINT(display_width=1), nullable=True),
        sa.Column("hidden", mysql.TINYINT(display_width=1), nullable=True),
        sa.Column("started_year", sa.Integer(), nullable=True),
        sa.Column("theme", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "entities_sections",
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
    )
    op.create_table(
        "groups_sections",
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("section_id", sa.Integer(), nullable=True),
        sa.Column("read", mysql.TINYINT(display_width=1), nullable=True),
        sa.Column("write", mysql.TINYINT(display_width=1), nullable=True),
        sa.Column("admin", mysql.TINYINT(display_width=1), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["section_id"],
            ["sections.id"],
        ),
    )
    op.create_index(
        op.f("ix_groups_sections_read"), "groups_sections", ["read"], unique=False
    )
    op.create_table(
        "mod_article",
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=64), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("text_source", sa.Text(), nullable=False),
        sa.Column("image", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["entities.id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "users_config",
        sa.Column("uid", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("forum_signature", sa.Text(), nullable=False),
        sa.Column("food_preferences", sa.Text(), nullable=False),
        sa.Column("card_no", sa.VARBINARY(length=50), nullable=True),
        sa.Column("enable_pay_by_card", mysql.TINYINT(display_width=1), nullable=False),
        sa.ForeignKeyConstraint(
            ["uid"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_table(
        "users_groups",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column(
            "start_time", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_groups")
    op.drop_table("users_config")
    op.drop_table("mod_article")
    op.drop_index(op.f("ix_groups_sections_read"), table_name="groups_sections")
    op.drop_table("groups_sections")
    op.drop_table("entities_sections")
    op.drop_table("users")
    op.drop_table("sections")
    op.drop_table("refresh_tokens")
    op.drop_table("groups")
    op.drop_table("entities")
    # ### end Alembic commands ###
